exclude:
  - node_modules
  - Semantic-UI
  - assets
  - dist/stylesheets/semantic_src.css
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - yarn.lock
  - package.json
  - postcss.json
  - postcss.config.js
  - LICENSE
watch_exclude: ['dist/']
encoding: UTF-8

permalink: /:categories/:title

title: Work Design
tagline: Site Tagline
production_url : https://work.design

navigation:
 - url: /
   title: 首页
 - url: /category
   title: 文章
 - url: /examples
   title: UI
 - url: /about
   title: 关于我们

lessc: 'date'
